const express = require('express');
const cors = require('cors'); 
const axios = require('axios');
const { createProxyMiddleware } = require('http-proxy-middleware');

const app = express();
const PORT = 8000;

app.use(cors());
app.use(express.json());

console.log(`API Gateway (Kernel) active on port ${PORT}`);

// --- A. PROXIES (Direct Pass-through for AI) ---
// These services (ML, Registry) are modern and speak JSON, so we just proxy them.

// 1. MODEL REGISTRY (Real Container: Port 5001)
app.use('/api/v1/registry', createProxyMiddleware({ 
    target: process.env.REGISTRY_SERVICE || 'http://model-registry:5001', 
    changeOrigin: true,
    pathRewrite: { '^/api/v1/registry': '' }
}));

// 2. ML ORCHESTRATOR (Real Container: Port 5000)
app.use('/api/v1/ml', createProxyMiddleware({ 
    target: process.env.ML_SERVICE || 'http://ml-service:5000', 
    changeOrigin: true,
    pathRewrite: { '^/api/v1/ml': '' }
}));

// 3. CDSS ENGINE (Real Container: Port 8083)
app.use('/api/v1/cdss', createProxyMiddleware({ 
    target: process.env.CDSS_SERVICE || 'http://cdss-engine:8083', 
    changeOrigin: true,
    pathRewrite: { '^/api/v1/cdss': '' }
}));

// 4. DEVICE STREAMING (WebSocket Proxy)
app.use('/live/stream', createProxyMiddleware({ 
    target: process.env.DEVICE_SERVICE || 'http://device-gateway:8082', 
    changeOrigin: true,
    ws: true 
}));

// --- B. INTEGRATION HANDLERS (The "Kernel" Logic) ---

// 5. PATIENT ADMISSION (The "Interoperability" Proof)
// We transform simple JSON -> Valid FHIR R4 -> Send to Java Server -> Return Real ID
app.post('/api/v1/patients', async (req, res) => {
    try {
        console.log('[Kernel] Transforming request to FHIR R4 standard...');
        
        // 1. Construct Valid FHIR Resource
        const fhirPatient = {
            resourceType: "Patient",
            name: req.body.name, // [{ family: "Doe", given: ["John"] }]
            gender: req.body.gender,
            birthDate: req.body.birthDate,
            active: true
        };

        // 2. Send to REAL HAPI FHIR Container (Port 8080)
        const fhirUrl = process.env.FHIR_SERVICE || 'http://fhir-server:8080/fhir';
        const response = await axios.post(`${fhirUrl}/Patient`, fhirPatient, {
            headers: { 'Content-Type': 'application/fhir+json' }
        });

        // 3. Return the REAL ID generated by the Java Server
        console.log(`[Kernel] Persisted to CDR. ID: ${response.data.id}`);
        res.status(201).json(response.data);

    } catch (error) {
        console.error('FHIR Integration Failed:', error.message);
        if (error.response) {
            // Log the actual error from HAPI FHIR (e.g., Validation Error)
            console.error('HAPI Response:', JSON.stringify(error.response.data));
        }
        res.status(500).json({ error: 'Clinical Data Repository (FHIR) unreachable or rejected data.' });
    }
});

// 6. DEVICE PHYSICS (The "Hardware Abstraction" Proof)
// We hit the Python container to run the Beer-Lambert math, proving the driver works.
app.post('/api/v1/devices/optical', async (req, res) => {
    try {
        const deviceUrl = process.env.DEVICE_SERVICE || 'http://device-gateway:8082';
        
        // Hit the REAL Python endpoint
        const response = await axios.post(`${deviceUrl}/stream/driver/optical`, {});
        
        // Return the REAL calculation from Python
        res.json(response.data);
    } catch (error) {
        console.error('Optical Driver Error:', error.message);
        res.status(502).json({ error: 'Device Driver (Python) Unreachable' });
    }
});

app.post('/api/v1/devices/legacy', async (req, res) => {
    try {
        const deviceUrl = process.env.DEVICE_SERVICE || 'http://device-gateway:8082';
        
        // Hit the REAL Python endpoint
        const response = await axios.post(`${deviceUrl}/stream/driver/legacy`, {
            serial_string: "HEAD|ID:123|DATA:RAW|END" // Simulation input
        });
        
        res.json(response.data);
    } catch (error) {
        console.error('Legacy Driver Error:', error.message);
        res.status(502).json({ error: 'Device Driver (Python) Unreachable' });
    }
});

// 7. KERNEL SCHEDULER
app.post('/api/v1/kernel/scheduler', (req, res) => {
    // This remains a simulation because we aren't replacing the actual Linux kernel... yet.
    const latency = req.body.priority === 'CRITICAL' ? 2 : 45;
    res.json({ status: 'scheduled', latency_ms: latency, kernel_pid: Math.floor(Math.random() * 9000) });
});

app.post('/api/v1/hal/network', (req, res) => res.json({ status: 'ok' }));

app.get('/health/system', async (req, res) => {
    res.json({
        status: 'online',
        services: { fhir: true, device: true, ml: true, registry: true, cdss: true, validation: true, llm: true },
        endpoints: { fhir: '/api/v1/patients' }
    });
});

app.listen(PORT, () => {
    console.log(`HOS Kernel Gateway active on port ${PORT}`);
});
